name: "publish-to-tidbyt"
description: "Publish to tidbyt"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "TIDBYT_API_TOKEN=${{ secrets.TIDBYT_API_TOKEN }}"
    - "TIDBYT_DEVICE_ID=${{ secrets.TIDBYT_DEVICE_ID }}"
    - "WHISTLE_EMAIL=${{ secrets.WHISTLE_EMAIL }}"
    - "WHISTLE_PASSWORD=${{ secrets.WHISTLE_PASSWORD }}"
    - "WHISTLE_PET=${{ secrets.WHISTLE_PET }}"
