name: "publish-to-tidbyt"
description: "Publish to tidbyt"
inputs:
  TIDBYT_API_TOKEN:
    description: "TIDBYT_API_TOKEN"
    required: true
  TIDBYT_DEVICE_ID:
    description: "TIDBYT_DEVICE_ID"
    required: true
  WHISTLE_EMAIL:
    description: "WHISTLE_EMAIL"
    required: true
  WHISTLE_PASSWORD:
    description: "WHISTLE_PASSWORD"
    required: true
  WHISTLE_PET:
    description: "WHISTLE_PET"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "TIDBYT_API_TOKEN=${{ inputs.TIDBYT_API_TOKEN }}"
    - "TIDBYT_DEVICE_ID=${{ inputs.TIDBYT_DEVICE_ID }}"
    - "WHISTLE_EMAIL=${{ inputs.WHISTLE_EMAIL }}"
    - "WHISTLE_PASSWORD=${{ inputs.WHISTLE_PASSWORD }}"
    - "WHISTLE_PET=${{ inputs.WHISTLE_PET }}"
